// ============================================
// Export Panel Component
// Export session data in various formats
// ============================================

'use client';

import { useState } from 'react';
import { Download, FileText, FileJson, Loader2, Sparkles } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn, formatDate, formatDuration, formatTime } from '@/lib/utils';
import { useSessionStore } from '@/stores/session';

interface ExportPanelProps {
  className?: string;
}

export function ExportPanel({ className }: ExportPanelProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [isGeneratingSummary, setIsGeneratingSummary] = useState(false);
  const [summary, setSummary] = useState<{ summary: string; themes: string[] } | null>(null);
  
  const { getExportData, transcript, displayHistory, startedAt } = useSessionStore();
  
  // Generate markdown export
  const exportMarkdown = () => {
    const data = getExportData();
    
    let md = `# Sermon Notes\n\n`;
    md += `**Date:** ${formatDate(data.startedAt || new Date())}\n\n`;
    md += `**Duration:** ${data.startedAt ? formatDuration(data.startedAt, data.endedAt) : 'N/A'}\n\n`;
    
    // Summary if available
    if (summary) {
      md += `## Summary\n\n${summary.summary}\n\n`;
      md += `### Key Themes\n\n${summary.themes.map(t => `- ${t}`).join('\n')}\n\n`;
    }
    
    // Scriptures
    md += `## Scriptures Referenced\n\n`;
    if (data.scriptures.length > 0) {
      data.scriptures.forEach((s) => {
        md += `### ${s.reference.reference}\n\n`;
        if (s.verseText) {
          md += `> "${s.verseText}"\n\n`;
        }
        md += `*Displayed at ${formatTime(s.displayedAt || new Date())}*\n\n`;
      });
    } else {
      md += `*No scriptures were displayed during this session.*\n\n`;
    }
    
    // Stats
    md += `## Statistics\n\n`;
    md += `- Scriptures Detected: ${data.stats.detected}\n`;
    md += `- Scriptures Approved: ${data.stats.approved}\n`;
    md += `- Scriptures Displayed: ${data.stats.displayed}\n`;
    md += `- Scriptures Dismissed: ${data.stats.dismissed}\n\n`;
    
    // Transcript
    if (data.transcript.length > 0) {
      md += `## Full Transcript\n\n`;
      md += data.transcript.map(s => s.text).join(' ');
      md += '\n';
    }
    
    md += `\n---\n*Generated by VerseCue*`;
    
    downloadFile(md, 'sermon-notes.md', 'text/markdown');
  };
  
  // Generate JSON export
  const exportJSON = () => {
    const data = getExportData();
    const json = JSON.stringify({
      ...data,
      summary: summary || null,
      generatedAt: new Date().toISOString(),
    }, null, 2);
    
    downloadFile(json, 'sermon-data.json', 'application/json');
  };
  
  // Download helper
  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  
  // Generate AI summary
  const generateSummary = async () => {
    if (transcript.length === 0) return;
    
    setIsGeneratingSummary(true);
    
    try {
      const transcriptText = transcript.map(s => s.text).join(' ');
      const scriptures = displayHistory.map(s => ({
        reference: s.reference.reference,
        displayedAt: s.displayedAt || new Date(),
      }));
      
      const response = await fetch('/api/summarize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ transcript: transcriptText, scriptures }),
      });
      
      if (response.ok) {
        const data = await response.json();
        setSummary(data);
      }
    } catch (error) {
      console.error('Failed to generate summary:', error);
    } finally {
      setIsGeneratingSummary(false);
    }
  };
  
  const hasData = transcript.length > 0 || displayHistory.length > 0;
  
  return (
    <div className={cn(
      'rounded-xl border border-verse-border bg-verse-surface p-5',
      className
    )}>
      <h3 className="font-body text-sm font-semibold text-verse-text tracking-wide uppercase mb-4">
        Export Session
      </h3>
      
      {/* Summary section */}
      <AnimatePresence>
        {summary && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="mb-4 p-4 rounded-xl bg-gold-500/10 border border-gold-500/20"
          >
            <div className="flex items-center gap-2 mb-2">
              <Sparkles className="w-4 h-4 text-gold-500" />
              <span className="text-xs font-semibold text-gold-400 uppercase tracking-wide">
                AI Summary
              </span>
            </div>
            <p className="text-sm text-verse-text/90 leading-relaxed mb-3">
              {summary.summary.substring(0, 200)}...
            </p>
            <div className="flex flex-wrap gap-2">
              {summary.themes.slice(0, 3).map((theme) => (
                <span
                  key={theme}
                  className="px-2 py-1 text-[10px] rounded-full bg-verse-border text-verse-subtle"
                >
                  {theme}
                </span>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
      
      {/* Export buttons */}
      <div className="space-y-2">
        {/* Generate Summary button */}
        {!summary && transcript.length > 0 && (
          <button
            onClick={generateSummary}
            disabled={isGeneratingSummary}
            className={cn(
              'w-full flex items-center justify-center gap-3 px-4 py-3 rounded-xl',
              'bg-gold-500/10 border border-gold-500/30 text-gold-400',
              'hover:bg-gold-500/20 transition-colors',
              'disabled:opacity-50 disabled:cursor-not-allowed'
            )}
          >
            {isGeneratingSummary ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4" />
            )}
            <span className="font-medium text-sm">
              {isGeneratingSummary ? 'Generating...' : 'Generate AI Summary'}
            </span>
          </button>
        )}
        
        {/* Export Markdown */}
        <button
          onClick={exportMarkdown}
          disabled={!hasData}
          className={cn(
            'w-full flex items-center justify-center gap-3 px-4 py-3 rounded-xl',
            'bg-verse-border/50 text-verse-text',
            'hover:bg-verse-border transition-colors',
            'disabled:opacity-50 disabled:cursor-not-allowed'
          )}
        >
          <FileText className="w-4 h-4" />
          <span className="font-medium text-sm">Export Markdown</span>
          <Download className="w-4 h-4 ml-auto opacity-50" />
        </button>
        
        {/* Export JSON */}
        <button
          onClick={exportJSON}
          disabled={!hasData}
          className={cn(
            'w-full flex items-center justify-center gap-3 px-4 py-3 rounded-xl',
            'bg-verse-border/50 text-verse-text',
            'hover:bg-verse-border transition-colors',
            'disabled:opacity-50 disabled:cursor-not-allowed'
          )}
        >
          <FileJson className="w-4 h-4" />
          <span className="font-medium text-sm">Export JSON</span>
          <Download className="w-4 h-4 ml-auto opacity-50" />
        </button>
      </div>
      
      {!hasData && (
        <p className="mt-3 text-[11px] text-verse-muted text-center">
          Start a session to enable exports
        </p>
      )}
    </div>
  );
}
